"use client"
import './globals.css'
import type { Metadata } from 'next'
import {Inter, Nunito} from 'next/font/google'
import { Provider } from 'react-redux'
import Home from './page'
import { PersistGate } from "redux-persist/integration/react";
import { usePathname } from "next/navigation"
import { store, persistor } from "@/redux/store"
import Header from "@/components/header/header"
import FooterPage from "@/components/footer/footer"
const inter = Inter({ subsets: ['latin'] })

const font = Nunito({
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Cineticket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  const pathname=usePathname();

  return (
    <html lang="en">
      <body className={font.className}>
      <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        {pathname==="/login"||pathname=="/signup"||pathname.includes("/admin")?<></>:<Header/>}
        {children}
        {pathname==="/login"||pathname=="/signup"||pathname.includes("/admin")?<></>: <FooterPage/>}
        </PersistGate>
      </Provider>
      </body>
    </html>
  )
}
